import Antivirus from "./antivirus";
import Audio from "./audio";
import BitLocker from "./bitlocker";
import Clipboard from "./clipboard";
import Camera from "./camera";
import Encryption from "./encryption";
import EventLogs from "./eventlogs";
import FileSystem from "./filesystem";
import Firewall from "./firewall";
import Localization from "./localization";
import Microphone from "./microphone";
import Network from "./network";
import Notification from "./notification";
import Power from "./power";
import Printer from "./printer";
import Regedit from "./regedit";
import Scheduler from "./scheduler";
import Screen from "./screen";
import Services from "./services";
import SystemInfo from "./systeminfo";
import TaskScheduler from "./taskscheduler";
import Taskmgr from "./taskmgr";
import UAC from "./uac";
import Users from "./users";
import USB from "./usb";
import WindowsUpdate from "./windowsupdate";
import Android from "./Android";
import SecPol from "./secpol";
import Msconfig from "./msconfig";
import AuditPolicy from "./auditpolicy";
import Certificates from "./certificates";
import Shell from "./shell";
import PsExec from "./PsExec";
import Mouse from "./Mouse";

export default class ManageOS {
  static readonly Android = Android;
  static readonly Antivirus = Antivirus;
  static readonly Audio = Audio;
  static readonly AuditPolicy = AuditPolicy;
  static readonly Bitlocker = BitLocker;
  static readonly Clipboard = Clipboard;
  static readonly Certificates = Certificates;
  static readonly Camera = Camera;
  static readonly Encryption = Encryption;
  static readonly EventLogs = EventLogs;
  static readonly FileSystem = FileSystem;
  static readonly Firewall = Firewall;
  static readonly Localization = Localization;
  static readonly Network = Network;
  static readonly Notification = Notification;
  static readonly Power = Power;
  static readonly Printer = Printer;
  static readonly Regedit = Regedit;
  static readonly SecPol = SecPol;
  static readonly Scheduler = Scheduler;
  static readonly Screen = Screen;
  static readonly Services = Services;
  static readonly SystemInfo = SystemInfo;
  static readonly Shell = Shell;
  static readonly Taskmgr = Taskmgr;
  static readonly TaskScheduler = TaskScheduler;
  static readonly UAC = UAC;
  static readonly USB = USB;
  static readonly Users = Users;
  static readonly WindowsUpdate = WindowsUpdate;
  static readonly Msconfig = Msconfig;
  static readonly Microphone = Microphone;
  static readonly PsExec = PsExec;
  static readonly Mouse = Mouse;
}
