import Antivirus from "./platforms/Windows/antivirus";
import Audio from "./platforms/Windows/audio";
import BitLocker from "./platforms/Windows/bitlocker";
import Clipboard from "./platforms/Windows/clipboard";
import Camera from "./platforms/Windows/camera";
import Encryption from "./platforms/Windows/encryption";
import EventLogs from "./platforms/Windows/eventlogs";
import FileSystem from "./platforms/Windows/filesystem";
import Firewall from "./platforms/Windows/firewall";
import Localization from "./platforms/Windows/localization";
import Microphone from "./platforms/Windows/microphone";
import Network from "./platforms/Windows/network";
import Notification from "./platforms/Windows/notification";
import Power from "./platforms/Windows/power";
import Printer from "./platforms/Windows/printer";
import Regedit from "./platforms/Windows/regedit";
import Scheduler from "./platforms/Windows/scheduler";
import Screen from "./platforms/Windows/screen";
import Services from "./platforms/Windows/services";
import SystemInfo from "./platforms/Windows/systeminfo";
import TaskScheduler from "./platforms/Windows/taskscheduler";
import Taskmgr from "./platforms/Windows/taskmgr";
import UAC from "./platforms/Windows/uac";
import Users from "./platforms/Windows/users";
import USB from "./platforms/Windows/usb";
import WindowsUpdate from "./platforms/Windows/windowsupdate";
import Android from "./platforms/Windows/Android";
import SecPol from "./platforms/Windows/secpol";
import Msconfig from "./platforms/Windows/msconfig";
import AuditPolicy from "./platforms/Windows/auditpolicy";
import Certificates from "./platforms/Windows/certificates";
import Shell from "./platforms/Windows/shell";
import PsExec from "./platforms/Windows/PsExec";
import Mouse from "./platforms/Windows/Mouse";
import Keyboard from "./platforms/Windows/Keyboard";
import Startup from "./platforms/Windows/startup";
import Server from "./platforms/Windows/Server";

export default class Windows {
  static readonly Android = Android;
  static readonly Antivirus = Antivirus;
  static readonly Audio = Audio;
  static readonly AuditPolicy = AuditPolicy;
  static readonly Bitlocker = BitLocker;
  static readonly Clipboard = Clipboard;
  static readonly Certificates = Certificates;
  static readonly Camera = Camera;
  static readonly Encryption = Encryption;
  static readonly EventLogs = EventLogs;
  static readonly FileSystem = FileSystem;
  static readonly Firewall = Firewall;
  static readonly Localization = Localization;
  static readonly Network = Network;
  static readonly Notification = Notification;
  static readonly Power = Power;
  static readonly Printer = Printer;
  static readonly Regedit = Regedit;
  static readonly SecPol = SecPol;
  static readonly Scheduler = Scheduler;
  static readonly Screen = Screen;
  static readonly Services = Services;
  static readonly SystemInfo = SystemInfo;
  static readonly Shell = Shell;
  static readonly Taskmgr = Taskmgr;
  static readonly TaskScheduler = TaskScheduler;
  static readonly UAC = UAC;
  static readonly USB = USB;
  static readonly Users = Users;
  static readonly WindowsUpdate = WindowsUpdate;
  static readonly Msconfig = Msconfig;
  static readonly Microphone = Microphone;
  static readonly PsExec = PsExec;
  static readonly Mouse = Mouse;
  static readonly Keyboard = Keyboard;
  static readonly Startup = Startup;
  static readonly Server = Server;
}
